version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Linting
          command: shellcheck git_clone_find
  test:
    docker:
      - image: bats/bats:v1.1.0
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: bats git_clone_find.bats

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test
