version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Linting
          command: shellcheck git_clone_find
  test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            git clone https://github.com/sstephenson/bats.git
            cd bats
            ./install.sh /usr/local
      - run:
          name: Unit Tests
          command: bats git_clone_find.bats

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test
