version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Linting
          command: make lint
  test:
    docker:
      - image: bats/bats:stable
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: make test

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test